apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  annotations:
    postgresql.db: DB_NAME
    postgresql.user: DB_USER
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world
